### PR TITLE
2 add refrash animation

### LINKED ISSUE #2: Add progress bar or ARC and auto regenerate function.
- [ARC](https://docs.zepp.com/docs/reference/device-app-api/hmUI/widget/ARC/)
- [image animation](https://docs.zepp.com/docs/reference/device-app-api/hmUI/widget/IMG_ANIM/)

Might be useful.
I'm working on this in my fork.

### PR DESCRIPTION
**Pull request by ZoLArk173**
Close #2

### CODE REVIEW

**Comment by ZoLArk173** [comment]
@Alpaca131

**Comment by Alpaca131** [comment]
I'll take a look at this later!

**Comment by Alpaca131** [comment]
I found a bug. The code won't reset when the screen got off before the ARC goes down.
I'm creating a patch of this.

**Comment by Alpaca131** [comment]
#6 This will fix it.

**Comment by Alpaca131** [comment]
@ZoLArk173 is this ok to merge? not in a hurry but just asking.

**Comment by ZoLArk173** [comment]
@Alpaca131 Oh I have been busy lately. Sorry for some delay🙏🙏. I have merged the #6. I didn't think of this bug before. Thanks!

**Comment by Alpaca131** [comment]
> @Alpaca131 Oh I have been busy lately. Sorry for some delay🙏🙏. I have merged the #6. I didn't think of this bug before. Thanks!

Sorry! I wasn't meant to bother you. 
Put yourself first.

**Pull request merged**
